### PR TITLE
Add more examples

### PR DESCRIPTION
**Pull request by SomeoneWeird**

### CODE REVIEW

**Comment by oleavr** [comment]
Awesome stuff! Is the blank line at the top of the scripts meant to be there btw?

**Comment by SomeoneWeird** [comment]
Fixed :)

**Comment by oleavr** [comment]
Sweet! :) One more thing, it would be great to adjust from:

`function() {`

to

`function () {`

(For named functions we do `function foo() {`, so basically there's always a space after `function`.

**Comment by SomeoneWeird** [comment]
Done :)

**Comment by oleavr** [comment]
Thanks!

**Pull request merged**
